[build]
  publish = "."

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Custom 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
